//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.TR_USER_COMPTE = new HashSet<TR_USER_COMPTE>();
        }
    
        public string ACC_CODE { get; set; }
        public string CMP_CODE { get; set; }
        public Nullable<short> HOLDING_FLAG { get; set; }
        public string HOLDING_CMP_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string BANK_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string CALENDAR_CODE { get; set; }
        public string CUR_CODE { get; set; }
        public string BANK_CUR_CODE { get; set; }
        public string ABK_CUR_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION2 { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string ADDRESS_3 { get; set; }
        public string ADDRESS_4 { get; set; }
        public string LEGAL_CODE { get; set; }
        public string AREA { get; set; }
        public Nullable<short> CUR_DEC_PLACES { get; set; }
        public string FILE_FORMAT { get; set; }
        public string ISSUER { get; set; }
        public Nullable<decimal> DRAFT_AUT_AMOUNT { get; set; }
        public Nullable<short> ACC_DISC_DATE_FLAG { get; set; }
        public string BIC_CODE { get; set; }
        public Nullable<short> OTHER_ID_TYPE { get; set; }
        public string OTHER_ID { get; set; }
        public string GL_ACC_CODE { get; set; }
        public string CORP_ID_CODE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_DEP { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public Nullable<short> FX_MIRRORING_FLAG { get; set; }
        public byte[] ROWVERSION { get; set; }
        public string ZU_01 { get; set; }
        public string ZU_02 { get; set; }
        public string ZU_03 { get; set; }
        public string ZU_04 { get; set; }
        public string ZU_05 { get; set; }
        public string ZU_06 { get; set; }
        public string ZU_07 { get; set; }
        public string ZU_08 { get; set; }
        public string ZU_09 { get; set; }
        public string ZU_10 { get; set; }
    
        public virtual ICollection<TR_USER_COMPTE> TR_USER_COMPTE { get; set; }
        public virtual COMPANy COMPANy { get; set; }
    }
}
