//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BK_MAN_LEDGER
    {
        public int MOVEMENT_ID { get; set; }
        public short SITE_NUMBER { get; set; }
        public string CMP_CODE { get; set; }
        public string BANK_CODE { get; set; }
        public string CUR_CODE { get; set; }
        public string BANK_CUR_CODE { get; set; }
        public string TRN_CUR_CODE { get; set; }
        public string FLOW_CODE { get; set; }
        public Nullable<System.DateTime> BOOK_DATE { get; set; }
        public Nullable<System.DateTime> VALUE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<short> AMOUNT_TYPE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string SIGNE { get; set; }
        public string ACC_CODE { get; set; }
        public int R_ACCOUNT_ID { get; set; }
        public Nullable<short> TRN_TYPE { get; set; }
        public Nullable<short> EXP_FLAG { get; set; }
        public Nullable<decimal> TRN_AMOUNT { get; set; }
        public Nullable<short> EXT_LENGHT { get; set; }
        public string IBC_ZONE_1 { get; set; }
        public string IBC_ZONE_2 { get; set; }
        public Nullable<short> BALANCE_TYPE { get; set; }
        public string REFERENCE_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> MVT_FEE { get; set; }
        public Nullable<short> FEE_SET { get; set; }
        public Nullable<short> DAYS_NBFIRST { get; set; }
        public Nullable<short> DIRECTION_FLAG { get; set; }
        public string COUNTER_PARTY_CODE { get; set; }
        public Nullable<int> INTEGRATION_SESSION { get; set; }
        public string COMPLEMENTS1 { get; set; }
        public string COMPLEMENTS2 { get; set; }
        public string COMPLEMENTS3 { get; set; }
        public string COMPLEMENTS4 { get; set; }
        public string COMPLEMENTS5 { get; set; }
        public string COMPLEMENTS6 { get; set; }
        public string COMPLEMENTS7 { get; set; }
        public string COMPLEMENTS8 { get; set; }
        public string COMPLEMENTS9 { get; set; }
        public string COMPLEMENTS10 { get; set; }
        public string COMPLEMENTS11 { get; set; }
        public string COMPLEMENTS12 { get; set; }
        public string COMPLEMENTS13 { get; set; }
        public string COMPLEMENTS14 { get; set; }
        public string COMPLEMENTS15 { get; set; }
        public string COMPLEMENTS16 { get; set; }
        public string COMPLEMENTS17 { get; set; }
        public string COMPLEMENTS18 { get; set; }
        public string COMPLEMENTS19 { get; set; }
        public string PJ { get; set; }
        public Nullable<bool> Ref { get; set; }
        public Nullable<bool> Validé { get; set; }
        public string ELECTRONIC_VALUE { get; set; }
        public Nullable<bool> Double_Ref { get; set; }
        public Nullable<decimal> SMNT { get; set; }
        public Nullable<System.DateTime> Date_Approbation { get; set; }
        public Nullable<bool> MAN_Reception { get; set; }
        public Nullable<System.DateTime> MAN_Date_reception { get; set; }
        public string MAN_Ref_Bord { get; set; }
        public string MAN_USER_Recp { get; set; }
        public Nullable<System.DateTime> ELEC_Date_Rat { get; set; }
        public Nullable<int> ELEC_Type_Rat { get; set; }
        public string ELEC_USER_Rat { get; set; }
        public Nullable<System.DateTime> Date_Valid { get; set; }
        public string USER_Valid { get; set; }
        public string SITE { get; set; }
        public string DESCRIPTIONCMP { get; set; }
        public Nullable<bool> PNP { get; set; }
        public Nullable<bool> MAN_Approbation { get; set; }
        public Nullable<System.DateTime> MAN_Date_Approbation { get; set; }
        public string MAN_Ref_Comptable { get; set; }
        public Nullable<bool> PP { get; set; }
        public string MAN_USER_App { get; set; }
        public Nullable<bool> PC { get; set; }
        public Nullable<System.DateTime> MAN_Date_Comptable { get; set; }
        public Nullable<bool> FS { get; set; }
        public Nullable<int> Id_Revision { get; set; }
        public Nullable<int> Id_Groupe_Utilisateur { get; set; }
        public string MAN_USR_COMP { get; set; }
        public Nullable<bool> E { get; set; }
        public Nullable<int> Id_Type_Document { get; set; }
        public string Ref_MFG { get; set; }
        public string Code_Client_MFG { get; set; }
        public string Code_Fournisseur_MFG { get; set; }
        public string Supl_MFG { get; set; }
        public Nullable<int> ID_PJ { get; set; }
        public Nullable<bool> Identifier { get; set; }
        public string ELEC_USR_identification { get; set; }
        public Nullable<System.DateTime> ELEC_Date_identification { get; set; }
        public Nullable<int> notification { get; set; }
        public Nullable<bool> Supp { get; set; }
        public string CMP_CODE_SITE { get; set; }
    
        public virtual TR_Revision TR_Revision { get; set; }
        public virtual TR_Groupe_Utilisateur TR_Groupe_Utilisateur { get; set; }
    }
}
