//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANy
    {
        public COMPANy()
        {
            this.TJ_USER_GROUPE = new HashSet<TJ_USER_GROUPE>();
            this.ACCOUNTs = new HashSet<ACCOUNT>();
        }
    
        public byte[] ROWVERSION { get; set; }
        public string CMP_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string CUR_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION2 { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string ADDRESS_3 { get; set; }
        public string ADDRESS_4 { get; set; }
        public string LEGAL_CODE { get; set; }
        public string AREA { get; set; }
        public Nullable<short> OTHER_ID_TYPE { get; set; }
        public string OTHER_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_DEP { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string CONTACT_FAX { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string ZU_01 { get; set; }
        public string ZU_02 { get; set; }
        public string ZU_03 { get; set; }
        public string ZU_04 { get; set; }
        public string ZU_05 { get; set; }
        public string ZU_06 { get; set; }
        public string ZU_07 { get; set; }
        public string ZU_08 { get; set; }
        public string ZU_09 { get; set; }
        public string ZU_10 { get; set; }
        public string CMP_SHORT_CODE { get; set; }
        public Nullable<short> COUNTERP_FLAG { get; set; }
        public Nullable<short> INTERMED_FLAG { get; set; }
        public string HOLDING_CMP { get; set; }
        public string SIGNATURE { get; set; }
        public string TAX_AUT_REGION { get; set; }
        public string TAX_AUT_NB { get; set; }
        public Nullable<System.DateTime> TAX_AUT_DATE { get; set; }
        public Nullable<short> CONSIDERAT_PERIOD { get; set; }
        public Nullable<short> RESIDENT_FLAG { get; set; }
        public string NNE { get; set; }
        public string WEB_ADDRESS { get; set; }
        public Nullable<short> INTERCHANGE_FLAG { get; set; }
        public byte[] LOGOTYPE { get; set; }
        public string VAT_CODE { get; set; }
        public Nullable<short> VAT_CALCULATION { get; set; }
        public Nullable<short> DIRECTION { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public Nullable<decimal> PROPORTION { get; set; }
    
        public virtual ICollection<TJ_USER_GROUPE> TJ_USER_GROUPE { get; set; }
        public virtual ICollection<ACCOUNT> ACCOUNTs { get; set; }
    }
}
