//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param_Login
    {
        public int UserId { get; set; }
        public string Matricule { get; set; }
        public string Login_User { get; set; }
        public string Mpt_User { get; set; }
        public Nullable<int> Est_Active { get; set; }
        public Nullable<System.DateTime> Date_Mod { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> EstPDG { get; set; }
        public Nullable<int> EstAdministrateur { get; set; }
        public string Departement { get; set; }
        public Nullable<int> Old_Id_User { get; set; }
        public Nullable<bool> Est_Administrateur { get; set; }
        public Nullable<bool> Est_Centralisateur { get; set; }
        public Nullable<bool> Est_Directeur { get; set; }
    
        public virtual Param_User Param_User { get; set; }
    }
}
