//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param_User
    {
        public Param_User()
        {
            this.Param_Login = new HashSet<Param_Login>();
            this.TJ_USER_GROUPE = new HashSet<TJ_USER_GROUPE>();
            this.TR_USER_COMPTE = new HashSet<TR_USER_COMPTE>();
            this.T_Transaction = new HashSet<T_Transaction>();
        }
    
        public string Matricule { get; set; }
        public string Identite { get; set; }
        public string Code_Filiale { get; set; }
        public Nullable<System.DateTime> Date_Mod { get; set; }
        public string Compte_LOTUS { get; set; }
        public string CIN_Resp { get; set; }
        public Nullable<bool> Est_PDG { get; set; }
        public Nullable<bool> Est_Administrateur { get; set; }
        public Nullable<bool> Est_Centralisateur { get; set; }
        public Nullable<bool> Est_Directeur { get; set; }
    
        public virtual ICollection<Param_Login> Param_Login { get; set; }
        public virtual ICollection<TJ_USER_GROUPE> TJ_USER_GROUPE { get; set; }
        public virtual ICollection<TR_USER_COMPTE> TR_USER_COMPTE { get; set; }
        public virtual ICollection<T_Transaction> T_Transaction { get; set; }
    }
}
