//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PBETSEntities1 : DbContext
    {
        public PBETSEntities1()
            : base("name=PBETSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public virtual DbSet<COMPANy> COMPANIES { get; set; }
        public virtual DbSet<Param_Login> Param_Login { get; set; }
        public virtual DbSet<Param_User> Param_User { get; set; }
        public virtual DbSet<T_SALARIES> T_SALARIES { get; set; }
        public virtual DbSet<TJ_USER_GROUPE> TJ_USER_GROUPE { get; set; }
        public virtual DbSet<TR_Groupe_Utilisateur> TR_Groupe_Utilisateur { get; set; }
        public virtual DbSet<TR_Type_Document> TR_Type_Document { get; set; }
        public virtual DbSet<TR_Type_Transaction> TR_Type_Transaction { get; set; }
        public virtual DbSet<TR_USER_BNK> TR_USER_BNK { get; set; }
        public virtual DbSet<TR_USER_COMPTE> TR_USER_COMPTE { get; set; }
        public virtual DbSet<TR_USER_FLUX> TR_USER_FLUX { get; set; }
        public virtual DbSet<TR_USER_Type> TR_USER_Type { get; set; }
        public virtual DbSet<TR_Type_Operation> TR_Type_Operation { get; set; }
        public virtual DbSet<TR_SITE_ACCPARTAGE> TR_SITE_ACCPARTAGE { get; set; }
        public virtual DbSet<TR_Mois> TR_Mois { get; set; }
        public virtual DbSet<BK_MAN_LEDGER> BK_MAN_LEDGER { get; set; }
        public virtual DbSet<TR_Revision> TR_Revision { get; set; }
        public virtual DbSet<V_USER_compte_type_WF_9> V_USER_compte_type_WF_9 { get; set; }
        public virtual DbSet<T_Transaction> T_Transaction { get; set; }
        public virtual DbSet<BK_MAN_REPORT> BK_MAN_REPORT { get; set; }
        public virtual DbSet<TR_Action> TR_Action { get; set; }
    
        public virtual ObjectResult<P_MAJ_PENP_Result> P_MAJ_PENP(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PENP_Result>("P_MAJ_PENP", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual int Comptabilisation_regroupper_parflux(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Comptabilisation_regroupper_parflux", id_pjParameter);
        }
    
        public virtual int Dupliquer_Bkman_report(Nullable<int> bK_MAN_REPORT_ID)
        {
            var bK_MAN_REPORT_IDParameter = bK_MAN_REPORT_ID.HasValue ?
                new ObjectParameter("BK_MAN_REPORT_ID", bK_MAN_REPORT_ID) :
                new ObjectParameter("BK_MAN_REPORT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Dupliquer_Bkman_report", bK_MAN_REPORT_IDParameter);
        }
    
        [DbFunction("PBETSEntities1", "get_lst_cmp_site")]
        public virtual IQueryable<string> get_lst_cmp_site(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[PBETSEntities1].[get_lst_cmp_site](@id_pj)", id_pjParameter);
        }
    
        public virtual int initialiser_DB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("initialiser_DB");
        }
    
        public virtual ObjectResult<Maj_Date_Operation_Result> Maj_Date_Operation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maj_Date_Operation_Result>("Maj_Date_Operation");
        }
    
        public virtual ObjectResult<Maj_Date_Operation_AMEN_Result> Maj_Date_Operation_AMEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maj_Date_Operation_AMEN_Result>("Maj_Date_Operation_AMEN");
        }
    
        public virtual int P_MAJ_BKML_RELEVE_MENSUEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MAJ_BKML_RELEVE_MENSUEL");
        }
    
        public virtual int P_MAJ_BKML_SUPP(Nullable<int> mOVEMENT_ID)
        {
            var mOVEMENT_IDParameter = mOVEMENT_ID.HasValue ?
                new ObjectParameter("MOVEMENT_ID", mOVEMENT_ID) :
                new ObjectParameter("MOVEMENT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MAJ_BKML_SUPP", mOVEMENT_IDParameter);
        }
    
        public virtual int P_MAJ_BKML_VERIF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MAJ_BKML_VERIF");
        }
    
        public virtual ObjectResult<P_MAJ_BKMLVERIF_Result> P_MAJ_BKMLVERIF(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction, Nullable<bool> afft)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            var afftParameter = afft.HasValue ?
                new ObjectParameter("afft", afft) :
                new ObjectParameter("afft", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_BKMLVERIF_Result>("P_MAJ_BKMLVERIF", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter, afftParameter);
        }
    
        public virtual ObjectResult<P_MAJ_BOR_rpt_Result> P_MAJ_BOR_rpt(string refb)
        {
            var refbParameter = refb != null ?
                new ObjectParameter("refb", refb) :
                new ObjectParameter("refb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_BOR_rpt_Result>("P_MAJ_BOR_rpt", refbParameter);
        }
    
        public virtual ObjectResult<P_MAJ_FSIB_PNP_Result> P_MAJ_FSIB_PNP(string rEFB)
        {
            var rEFBParameter = rEFB != null ?
                new ObjectParameter("REFB", rEFB) :
                new ObjectParameter("REFB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_FSIB_PNP_Result>("P_MAJ_FSIB_PNP", rEFBParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PC_Result> P_MAJ_PC(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PC_Result>("P_MAJ_PC", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PC_rpt_Result> P_MAJ_PC_rpt(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PC_rpt_Result>("P_MAJ_PC_rpt", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PCC_rpt_Result> P_MAJ_PCC_rpt(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PCC_rpt_Result>("P_MAJ_PCC_rpt", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PEC_Result> P_MAJ_PEC(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PEC_Result>("P_MAJ_PEC", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PEC_rpt_Result> P_MAJ_PEC_rpt(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PEC_rpt_Result>("P_MAJ_PEC_rpt", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PECC_rpt_Result> P_MAJ_PECC_rpt(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PECC_rpt_Result>("P_MAJ_PECC_rpt", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PEP_Result> P_MAJ_PEP(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PEP_Result>("P_MAJ_PEP", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PEP_rpt_Result> P_MAJ_PEP_rpt(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PEP_rpt_Result>("P_MAJ_PEP_rpt", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PNP_Result> P_MAJ_PNP(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PNP_Result>("P_MAJ_PNP", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PNP_ALL_Result> P_MAJ_PNP_ALL(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PNP_ALL_Result>("P_MAJ_PNP_ALL", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PNP_verif_Result> P_MAJ_PNP_verif(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PNP_verif_Result>("P_MAJ_PNP_verif", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PNP_verif_all_Result> P_MAJ_PNP_verif_all(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PNP_verif_all_Result>("P_MAJ_PNP_verif_all", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PNPRV_Result> P_MAJ_PNPRV(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PNPRV_Result>("P_MAJ_PNPRV", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PP_Result> P_MAJ_PP(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PP_Result>("P_MAJ_PP", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PP_rpt_Result> P_MAJ_PP_rpt(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PP_rpt_Result>("P_MAJ_PP_rpt", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual ObjectResult<P_MAJ_PPRV_Result> P_MAJ_PPRV(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MAJ_PPRV_Result>("P_MAJ_PPRV", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual int P_MAJ_SERVICE(Nullable<int> iD, Nullable<int> srv, Nullable<int> notif)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var srvParameter = srv.HasValue ?
                new ObjectParameter("srv", srv) :
                new ObjectParameter("srv", typeof(int));
    
            var notifParameter = notif.HasValue ?
                new ObjectParameter("notif", notif) :
                new ObjectParameter("notif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MAJ_SERVICE", iDParameter, srvParameter, notifParameter);
        }
    
        public virtual ObjectResult<P_TDB_PNP_ALL_Result> P_TDB_PNP_ALL(Nullable<System.DateTime> du, Nullable<System.DateTime> au, string cmp_code, string matricule, string aCC_CODE)
        {
            var duParameter = du.HasValue ?
                new ObjectParameter("du", du) :
                new ObjectParameter("du", typeof(System.DateTime));
    
            var auParameter = au.HasValue ?
                new ObjectParameter("au", au) :
                new ObjectParameter("au", typeof(System.DateTime));
    
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_TDB_PNP_ALL_Result>("P_TDB_PNP_ALL", duParameter, auParameter, cmp_codeParameter, matriculeParameter, aCC_CODEParameter);
        }
    
        public virtual ObjectResult<P_WF_MAJ_PEC_Result> P_WF_MAJ_PEC(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee, Nullable<int> type_Transaction)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            var type_TransactionParameter = type_Transaction.HasValue ?
                new ObjectParameter("Type_Transaction", type_Transaction) :
                new ObjectParameter("Type_Transaction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_WF_MAJ_PEC_Result>("P_WF_MAJ_PEC", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter, type_TransactionParameter);
        }
    
        public virtual int RATTACHEMENT_AMEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RATTACHEMENT_AMEN");
        }
    
        public virtual ObjectResult<RATTACHEMENT_BIAT_Result> RATTACHEMENT_BIAT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RATTACHEMENT_BIAT_Result>("RATTACHEMENT_BIAT");
        }
    
        public virtual ObjectResult<RATTACHEMENT_BIAT1_Result> RATTACHEMENT_BIAT1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RATTACHEMENT_BIAT1_Result>("RATTACHEMENT_BIAT1");
        }
    
        public virtual ObjectResult<RATTACHEMENT_BIAT11_Result> RATTACHEMENT_BIAT11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RATTACHEMENT_BIAT11_Result>("RATTACHEMENT_BIAT11");
        }
    
        public virtual int rattachement_FSIB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rattachement_FSIB");
        }
    
        public virtual int RATTACHEMENT_UBCI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RATTACHEMENT_UBCI");
        }
    
        public virtual int RATTACHEMNT_ALL_BANK_SCAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RATTACHEMNT_ALL_BANK_SCAN");
        }
    
        public virtual int RATTACHEMNT_BANK_SCAN_Structurer(Nullable<int> id_mov, string pj, string nF)
        {
            var id_movParameter = id_mov.HasValue ?
                new ObjectParameter("id_mov", id_mov) :
                new ObjectParameter("id_mov", typeof(int));
    
            var pjParameter = pj != null ?
                new ObjectParameter("pj", pj) :
                new ObjectParameter("pj", typeof(string));
    
            var nFParameter = nF != null ?
                new ObjectParameter("NF", nF) :
                new ObjectParameter("NF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RATTACHEMNT_BANK_SCAN_Structurer", id_movParameter, pjParameter, nFParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int Sp_Exec_Insert(string txt)
        {
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Exec_Insert", txtParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_MAJ_PREV_Result> SP_MAJ_PREV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAJ_PREV_Result>("SP_MAJ_PREV");
        }
    
        public virtual int Sp_Notification_Apre_Apprbation(string matricule)
        {
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Notification_Apre_Apprbation", matriculeParameter);
        }
    
        public virtual int Sp_Notification_Mes_Taches(string id_pj)
        {
            var id_pjParameter = id_pj != null ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Notification_Mes_Taches", id_pjParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_WF(Nullable<int> id, string matricule)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("Matricule", matricule) :
                new ObjectParameter("Matricule", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_WF", idParameter, matriculeParameter);
        }
    
        public virtual int SP_WFC(Nullable<int> id, string matricule, Nullable<int> id_pj, string commentaire)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("Matricule", matricule) :
                new ObjectParameter("Matricule", typeof(string));
    
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            var commentaireParameter = commentaire != null ?
                new ObjectParameter("commentaire", commentaire) :
                new ObjectParameter("commentaire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_WFC", idParameter, matriculeParameter, id_pjParameter, commentaireParameter);
        }
    
        [DbFunction("PBETSEntities1", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[PBETSEntities1].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int TDB_SUVI_J(Nullable<System.DateTime> duj, Nullable<System.DateTime> auj, string utilisateur)
        {
            var dujParameter = duj.HasValue ?
                new ObjectParameter("duj", duj) :
                new ObjectParameter("duj", typeof(System.DateTime));
    
            var aujParameter = auj.HasValue ?
                new ObjectParameter("auj", auj) :
                new ObjectParameter("auj", typeof(System.DateTime));
    
            var utilisateurParameter = utilisateur != null ?
                new ObjectParameter("utilisateur", utilisateur) :
                new ObjectParameter("utilisateur", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TDB_SUVI_J", dujParameter, aujParameter, utilisateurParameter);
        }
    
        public virtual int ZZ_AVIS_Instance(string filePath, string fileRes, string fileNameMask, Nullable<bool> aLL)
        {
            var filePathParameter = filePath != null ?
                new ObjectParameter("FilePath", filePath) :
                new ObjectParameter("FilePath", typeof(string));
    
            var fileResParameter = fileRes != null ?
                new ObjectParameter("FileRes", fileRes) :
                new ObjectParameter("FileRes", typeof(string));
    
            var fileNameMaskParameter = fileNameMask != null ?
                new ObjectParameter("FileNameMask", fileNameMask) :
                new ObjectParameter("FileNameMask", typeof(string));
    
            var aLLParameter = aLL.HasValue ?
                new ObjectParameter("ALL", aLL) :
                new ObjectParameter("ALL", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ZZ_AVIS_Instance", filePathParameter, fileResParameter, fileNameMaskParameter, aLLParameter);
        }
    
        public virtual ObjectResult<PB_Comptabilisees_Result> PB_Comptabilisees(string cmp_code, string matricule, string aCC_CODE, Nullable<int> mois, Nullable<int> annee)
        {
            var cmp_codeParameter = cmp_code != null ?
                new ObjectParameter("cmp_code", cmp_code) :
                new ObjectParameter("cmp_code", typeof(string));
    
            var matriculeParameter = matricule != null ?
                new ObjectParameter("matricule", matricule) :
                new ObjectParameter("matricule", typeof(string));
    
            var aCC_CODEParameter = aCC_CODE != null ?
                new ObjectParameter("ACC_CODE", aCC_CODE) :
                new ObjectParameter("ACC_CODE", typeof(string));
    
            var moisParameter = mois.HasValue ?
                new ObjectParameter("mois", mois) :
                new ObjectParameter("mois", typeof(int));
    
            var anneeParameter = annee.HasValue ?
                new ObjectParameter("annee", annee) :
                new ObjectParameter("annee", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PB_Comptabilisees_Result>("PB_Comptabilisees", cmp_codeParameter, matriculeParameter, aCC_CODEParameter, moisParameter, anneeParameter);
        }
    }
}
