//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SALARIES
    {
        public string Matricule { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Nom_Jeune_Fille { get; set; }
        public string Nom_Prenom { get; set; }
        public Nullable<System.DateTime> Date_Anciennete_Groupe { get; set; }
        public Nullable<System.DateTime> Date_Anciennete_Societe { get; set; }
        public string Code_Sexe { get; set; }
        public string Libelle_Sexe { get; set; }
        public Nullable<System.DateTime> Date_Naissance { get; set; }
        public string Code_Pays_Naissance { get; set; }
        public string Libelle_Pays_Naissance { get; set; }
        public string Code_Gouv_Naissance { get; set; }
        public string Libelle_Gouv_Naissance { get; set; }
        public string Code_Ville_Naissance { get; set; }
        public string Libelle_Ville_Naissance { get; set; }
        public string Code_Etablissement_Paie { get; set; }
        public string Libelle_Etablissement_Paie { get; set; }
        public string Compte_Windows { get; set; }
        public string Compte_Lotus { get; set; }
        public string Abreviation_Lotus { get; set; }
        public string Adresse_IP { get; set; }
        public string Temoin_Utilisateur_Informatique { get; set; }
        public string Temoin_Acces_Reseau_Siege { get; set; }
        public string Matricule_Responsable { get; set; }
        public string Nom_Prenom_Responsable { get; set; }
        public string Compte_Lotus_Responsable { get; set; }
        public string Matricule_Coordinateur { get; set; }
        public string Nom_Prenom_Coordinateur { get; set; }
        public string Compte_Lotus_Coordinateur { get; set; }
        public string Matricule_Directeur { get; set; }
        public string Nom_Prenom_Directeur { get; set; }
        public string Compte_Lotus_Directeur { get; set; }
        public string Code_Situation_Familiale { get; set; }
        public string Libelle_Situation_Familiale { get; set; }
        public Nullable<System.DateTime> Date_debut_Contrat { get; set; }
        public string Type_Nature_Contrat { get; set; }
        public string Libelle_Type_Contrat { get; set; }
        public Nullable<System.DateTime> Dat_Eff_Col { get; set; }
        public string Code_College { get; set; }
        public string Libelle_College { get; set; }
        public Nullable<System.DateTime> Dat_Eff_Affectation { get; set; }
        public string Code_Poste { get; set; }
        public string Libelle_Poste { get; set; }
        public string Code_Unite { get; set; }
        public string Libelle_Unite { get; set; }
        public string Code_Etablissement_Affectation { get; set; }
        public string Libelle_Etablissement_Affectation { get; set; }
        public Nullable<int> Niveau_Hierarchique { get; set; }
        public Nullable<System.DateTime> Date_Mvt { get; set; }
    }
}
