//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Transaction
    {
        public int Id_Transaction { get; set; }
        public Nullable<int> MOVEMENT_ID { get; set; }
        public string Matricule { get; set; }
        public Nullable<System.DateTime> DateAction { get; set; }
        public Nullable<int> Id_Action { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Param_User Param_User { get; set; }
    }
}
