//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Groupe_Utilisateur
    {
        public TR_Groupe_Utilisateur()
        {
            this.TR_USER_FLUX = new HashSet<TR_USER_FLUX>();
            this.TJ_USER_GROUPE = new HashSet<TJ_USER_GROUPE>();
            this.TR_Type_Operation = new HashSet<TR_Type_Operation>();
            this.BK_MAN_LEDGER = new HashSet<BK_MAN_LEDGER>();
        }
    
        public int Id_Groupe_Utilisateur { get; set; }
        public string Libelle_Groupe_Utilisateur { get; set; }
        public string Description_Role { get; set; }
    
        public virtual ICollection<TR_USER_FLUX> TR_USER_FLUX { get; set; }
        public virtual ICollection<TJ_USER_GROUPE> TJ_USER_GROUPE { get; set; }
        public virtual ICollection<TR_Type_Operation> TR_Type_Operation { get; set; }
        public virtual ICollection<BK_MAN_LEDGER> BK_MAN_LEDGER { get; set; }
    }
}
