//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Revision
    {
        public TR_Revision()
        {
            this.BK_MAN_LEDGER = new HashSet<BK_MAN_LEDGER>();
        }
    
        public int Id_Revision { get; set; }
        public string Libelle_Revision { get; set; }
    
        public virtual ICollection<BK_MAN_LEDGER> BK_MAN_LEDGER { get; set; }
    }
}
