//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_SITE_ACCPARTAGE
    {
        public int Site { get; set; }
        public string Libelle_Site { get; set; }
        public Nullable<bool> Acc_partage { get; set; }
    }
}
