//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Type_Operation
    {
        public int Id_op { get; set; }
        public string BANK_CODE { get; set; }
        public string Code_Operation { get; set; }
        public string Libelle_Operation { get; set; }
        public Nullable<int> Id_Groupe_Utilisateur { get; set; }
        public Nullable<int> Id_Type_Document { get; set; }
    
        public virtual TR_USER_BNK TR_USER_BNK { get; set; }
        public virtual TR_Type_Document TR_Type_Document { get; set; }
        public virtual TR_Groupe_Utilisateur TR_Groupe_Utilisateur { get; set; }
    }
}
