//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_USER_COMPTE
    {
        public int id_User_Compte { get; set; }
        public string Matricule { get; set; }
        public string ACC_CODE { get; set; }
        public Nullable<int> Id_Type_Utilisateur { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual Param_User Param_User { get; set; }
        public virtual TR_USER_Type TR_USER_Type { get; set; }
    }
}
