//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_USER_Type
    {
        public TR_USER_Type()
        {
            this.TR_USER_COMPTE = new HashSet<TR_USER_COMPTE>();
        }
    
        public int Id_Type_Utilisateur { get; set; }
        public string Libelle_Type_Utilisateur { get; set; }
    
        public virtual ICollection<TR_USER_COMPTE> TR_USER_COMPTE { get; set; }
    }
}
