//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_USER_BNK
    {
        public TR_USER_BNK()
        {
            this.TR_USER_FLUX = new HashSet<TR_USER_FLUX>();
            this.TR_Type_Operation = new HashSet<TR_Type_Operation>();
        }
    
        public string BANK_Code { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Electronique { get; set; }
    
        public virtual ICollection<TR_USER_FLUX> TR_USER_FLUX { get; set; }
        public virtual ICollection<TR_Type_Operation> TR_Type_Operation { get; set; }
    }
}
