//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_compte_type_WF_9
    {
        public string ACC_CODE { get; set; }
        public int Electronique { get; set; }
        public int Id_Type_Utilisateur { get; set; }
        public string Matricule { get; set; }
        public string DESCRIPTION { get; set; }
        public string CMP_CODE { get; set; }
        public string Site { get; set; }
        public string BANK_CODE { get; set; }
    }
}
